# INFO ENDPOINT CONFIGURATION
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "1.0-SNAPSHOT"
    encoding: "UTF-8"
    java.vendor: "Oracle Corporation"
    java.version: "23.0.2"

openapi:
  pessoas:
    base-path:

server:
  port: 8443
  servlet:
    context-path: /pessoas/api
#  ssl:
#    certificate: "classpath:at_hand.crt"
#    certificate-private-key: "classpath:at_hand.key"

spring:
  flyway:
    schemas: people-registration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: people-registration
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        temp.use_jdbc_metadata_defaults: false
        jdbc.time_zone: UTC
    show-sql: false
  messages:
    basename: messages/messages
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  profiles:
    active: ${profiles_active:local}
  output:
    ansi:
      enabled: always

springdoc:
  swagger-ui:
    syntaxHighlight:
      theme: tomorrow-night

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,loggers,metrics,startup,prometheus"
  health:
    diskspace:
      enabled: false
    ssl:
      enabled: false
  info:
    git:
      mode: full
otel:
  service:
    name: test
