version: "3.0"
services:
  postgres:
    image: postgres:17
    container_name: pr_postgres
    networks:
      - pr_network
    environment:
      POSTGRES_USER: apppr
      POSTGRES_PASSWORD: pswpr
      POSTGRES_DB: people-registration
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
  rabbit:
    image: rabbitmq:4.1-management
    container_name: pr_rabbitmq
    networks:
      - pr_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq:rw
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: pr_mongodb
    networks:
      - pr_network
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
  people-registration:
    image: people-registration-api:1.0-SNAPSHOT
    container_name: people-registration-api
    networks:
      - pr_network
    environment:
      MONGO_URL: mongodb://pr_mongodb:27017/people-registration
      POSTGRESQL_URL: jdbc:postgresql://pr_postgres:5432/people-registration
      POSTGRESQL_USER: apppr
      POSTGRESQL_PASSWORD: pswpr
      RABBIT_HOST: pr_rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    ports:
      - "8080:8080"
  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    networks:
      - pr_network
    ports:
      - "9411:9411"
  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: prometheus
    networks:
      - pr_network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
networks:
  pr_network:
    driver: bridge
