version: "3.0"
services:
  postgres:
    image: postgres:17
    container_name: pr_postgres
    networks:
      - pr_network
    environment:
      POSTGRES_USER: apppr
      POSTGRES_PASSWORD: pswpr
      POSTGRES_DB: people-registration
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
  rabbit:
    image: rabbitmq:4.1-management
    container_name: pr_rabbitmq
    networks:
      - pr_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq:rw
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: pr_mongodb
    networks:
      - pr_network
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
networks:
  pr_network:
    driver: bridge
