global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: people-registration
    fallback_scrape_protocol: PrometheusText0.0.4
    metrics_path: /pessoas/api/actuator/prometheus
    static_configs:
      - targets: ['people-registration-api:8080']
