# INFO ENDPOINT CONFIGURATION
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java.vendor: "@java.vendor@"
    java.version: "@java.version@"

server:
  servlet:
    context-path: /pessoas/api

spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  flyway:
    schemas: people-registration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: people-registration
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        temp.use_jdbc_metadata_defaults: false
        jdbc.time_zone: UTC
    show-sql: false
  messages:
    basename: messages/messages
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  profiles:
    active: ${PROFILES}
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

springdoc:
  swagger-ui:
    syntaxHighlight:
      theme: tomorrow-night

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,loggers,metrics,startup,prometheus"
  health:
    diskspace:
      enabled: false
    ssl:
      enabled: false
  info:
    git:
      mode: full

